# 并发引擎
concurrency:
  loop: -1       # 循环次数 1 一次  -1 无限循环
  unit: s                # s 秒 、m 分钟 、h 小时
  stages:
    - duration: 10            # 第一阶段：1分钟内都按100并发执行任务
      target: 1
    - duration: 20            # 第二阶段：1-2分钟保持200并发
      target: 2
    - duration: 30            # 第三阶段：2-5分钟保持300并发
      target: 3
    - duration: 40            # 第四阶段：5-10分钟保持200并发
      target: 2
    - duration: 50            # 第四阶段：保持200并发1分钟
      target: 1

# 全局配置
global:
    gd_host: https://gd.ygcx.com

# 文件读取
reader:
    type: csv
    file: /Users/edy/Desktop/data.csv
# 请求链
requests:
  - name: 询价
    url: "https://example.com/api"
    method: GET
    headers:
      Authorization: "Bearer xyz"
    params:
      query: "test"
    assertions:
      - status_code: 200
      - response_time: <500
  - name: 询价
    url: "https://example.com/api"
    method: GET
    headers:
        Authorization: "{token}"
    params:
    query: "test"
    assertions:
    - status_code: 200
    - response_time: <500