app:
    listen: :8080
concurrency:
    loop: 1
    unit: s
    stages:
        - label: 预热
          duration: 10
          target: 2
        - label: 稳定
          duration: 30
          target: 6
        - label: 冲刺
          duration: 59
          target: 12
        - label: 冲刺
          duration: 60
          target: 12
        - duration: 71
          target: 20
        - duration: 79
          target: 12
        - duration: 87
          target: 8
        - duration: 91
          target: 6
        - duration: 94
          target: 4
        - duration: 96
          target: 20
        - duration: 102
          target: 20
        - duration: 111
          target: 1
        - duration: 112
          target: 0
reader:
    type: csv
    file: config/data/meituan_yace_data.csv
global:
    host: https://postman-echo.com
    scene: quickpress
requests:
    - name: 询价
      method: GET
      url: ${host}/get
      timeout_ms: 3000
      headers:
        X-Scene: ${scene}
      query:
        endPointLat: ${e_lat}
        endPointLng: ${e_lng}
        keyword: hello
        scene: ${scene}
        startPointLat: ${s_lat}
        startPointLng: ${s_lng}
        startPointName: yace_sname
      expected_status: 200
      contains:
        - hello
